### ISSUE TITLE
Update Config Backup & Restore re format, sensitive contents, and rpm backup mechanism

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#465]
Collating:

- [ ]  Add small section on config backup file structure #359
- [ ]  @daniel-illi  comment https://github.com/rockstor/rockstor-core/issues/1699#issuecomment-314392735 re sensitive contents note.
- [ ] Doc additions re rockstor-core Issue/PR: "Save and Restore config back-up files during rpm update #2660" #2661
